- project:
    check:
      jobs:
        - networking-calico-tempest-dsvm-rocky
        - networking-calico-tempest-dsvm-master
    gate:
      jobs:
        - networking-calico-tempest-dsvm-rocky
    periodic:
      jobs:
        - networking-calico-tempest-dsvm-master:
            branches: master

- job:
    name: networking-calico-tempest-dsvm-rocky
    vars:
      branch_override: stable/rocky
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-dsvm-networking-calico/run.yaml
    post-run: playbooks/legacy/tempest-dsvm-networking-calico/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/networking-calico
      - openstack/tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$

- job:
    name: networking-calico-tempest-dsvm-master
    voting: false
    parent: legacy-dsvm-base
    run: playbooks/legacy/tempest-dsvm-networking-calico/run.yaml
    post-run: playbooks/legacy/tempest-dsvm-networking-calico/post.yaml
    timeout: 7800
    required-projects:
      - openstack/devstack-gate
      - openstack/networking-calico
      - openstack/tempest
    irrelevant-files:
      - ^(test-|)requirements.txt$
      - ^setup.cfg$
